// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/gz14.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ Error Codes ============
type ErrCode int32

const (
	ErrCode_ERR_OK                ErrCode = 0
	ErrCode_ERR_UNKNOWN           ErrCode = 1000
	ErrCode_ERR_INVALID_MSG       ErrCode = 1001
	ErrCode_ERR_ACCOUNT_NOT_FOUND ErrCode = 2001
	ErrCode_ERR_WRONG_PASSWORD    ErrCode = 2002
	ErrCode_ERR_ACCOUNT_EXIST     ErrCode = 2003
	ErrCode_ERR_ROLE_NAME_EXIST   ErrCode = 3001
	ErrCode_ERR_ROLE_FULL         ErrCode = 3002
	ErrCode_ERR_ROLE_NOT_FOUND    ErrCode = 3003
	ErrCode_ERR_SESSION_INVALID   ErrCode = 4001
	ErrCode_ERR_SESSION_EXPIRED   ErrCode = 4002
	ErrCode_ERR_LOGIN_REPEATED    ErrCode = 4003
	ErrCode_ERR_SCENE_FULL        ErrCode = 5001
	ErrCode_ERR_MOVE_TOO_FAST     ErrCode = 5002
	ErrCode_ERR_OUT_OF_BOUNDS     ErrCode = 5003
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "ERR_OK",
		1000: "ERR_UNKNOWN",
		1001: "ERR_INVALID_MSG",
		2001: "ERR_ACCOUNT_NOT_FOUND",
		2002: "ERR_WRONG_PASSWORD",
		2003: "ERR_ACCOUNT_EXIST",
		3001: "ERR_ROLE_NAME_EXIST",
		3002: "ERR_ROLE_FULL",
		3003: "ERR_ROLE_NOT_FOUND",
		4001: "ERR_SESSION_INVALID",
		4002: "ERR_SESSION_EXPIRED",
		4003: "ERR_LOGIN_REPEATED",
		5001: "ERR_SCENE_FULL",
		5002: "ERR_MOVE_TOO_FAST",
		5003: "ERR_OUT_OF_BOUNDS",
	}
	ErrCode_value = map[string]int32{
		"ERR_OK":                0,
		"ERR_UNKNOWN":           1000,
		"ERR_INVALID_MSG":       1001,
		"ERR_ACCOUNT_NOT_FOUND": 2001,
		"ERR_WRONG_PASSWORD":    2002,
		"ERR_ACCOUNT_EXIST":     2003,
		"ERR_ROLE_NAME_EXIST":   3001,
		"ERR_ROLE_FULL":         3002,
		"ERR_ROLE_NOT_FOUND":    3003,
		"ERR_SESSION_INVALID":   4001,
		"ERR_SESSION_EXPIRED":   4002,
		"ERR_LOGIN_REPEATED":    4003,
		"ERR_SCENE_FULL":        5001,
		"ERR_MOVE_TOO_FAST":     5002,
		"ERR_OUT_OF_BOUNDS":     5003,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gz14_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_proto_gz14_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{0}
}

// ============ Common ============
type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_proto_gz14_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{0}
}

func (x *Vec2) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	MapId         int32                  `protobuf:"varint,4,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_proto_gz14_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerInfo) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *PlayerInfo) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

// ============ Lobby: Login ============
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_proto_gz14_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       ErrCode                `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,enum=gz14.ErrCode" json:"err_code,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	SceneAddr     string                 `protobuf:"bytes,3,opt,name=scene_addr,json=sceneAddr,proto3" json:"scene_addr,omitempty"`
	Roles         []*PlayerInfo          `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	mi := &file_proto_gz14_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRsp) GetErrCode() ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return ErrCode_ERR_OK
}

func (x *LoginRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRsp) GetSceneAddr() string {
	if x != nil {
		return x.SceneAddr
	}
	return ""
}

func (x *LoginRsp) GetRoles() []*PlayerInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// ============ Lobby: Register ============
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_proto_gz14_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       ErrCode                `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,enum=gz14.ErrCode" json:"err_code,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRsp) Reset() {
	*x = RegisterRsp{}
	mi := &file_proto_gz14_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRsp) ProtoMessage() {}

func (x *RegisterRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRsp.ProtoReflect.Descriptor instead.
func (*RegisterRsp) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRsp) GetErrCode() ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return ErrCode_ERR_OK
}

func (x *RegisterRsp) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// ============ Lobby: CreateRole ============
type CreateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReq) Reset() {
	*x = CreateRoleReq{}
	mi := &file_proto_gz14_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReq) ProtoMessage() {}

func (x *CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReq.ProtoReflect.Descriptor instead.
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoleReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRoleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       ErrCode                `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,enum=gz14.ErrCode" json:"err_code,omitempty"`
	Role          *PlayerInfo            `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRsp) Reset() {
	*x = CreateRoleRsp{}
	mi := &file_proto_gz14_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRsp) ProtoMessage() {}

func (x *CreateRoleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRsp.ProtoReflect.Descriptor instead.
func (*CreateRoleRsp) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRoleRsp) GetErrCode() ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return ErrCode_ERR_OK
}

func (x *CreateRoleRsp) GetRole() *PlayerInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

// ============ Lobby → Scene: EnterScene ============
type EnterSceneReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterSceneReq) Reset() {
	*x = EnterSceneReq{}
	mi := &file_proto_gz14_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterSceneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneReq) ProtoMessage() {}

func (x *EnterSceneReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneReq.ProtoReflect.Descriptor instead.
func (*EnterSceneReq) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{8}
}

func (x *EnterSceneReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnterSceneReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type EnterSceneRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       ErrCode                `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,enum=gz14.ErrCode" json:"err_code,omitempty"`
	MapId         int32                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	AoiPlayers    []*PlayerInfo          `protobuf:"bytes,4,rep,name=aoi_players,json=aoiPlayers,proto3" json:"aoi_players,omitempty"` // 周围玩家列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterSceneRsp) Reset() {
	*x = EnterSceneRsp{}
	mi := &file_proto_gz14_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterSceneRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneRsp) ProtoMessage() {}

func (x *EnterSceneRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneRsp.ProtoReflect.Descriptor instead.
func (*EnterSceneRsp) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{9}
}

func (x *EnterSceneRsp) GetErrCode() ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return ErrCode_ERR_OK
}

func (x *EnterSceneRsp) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *EnterSceneRsp) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EnterSceneRsp) GetAoiPlayers() []*PlayerInfo {
	if x != nil {
		return x.AoiPlayers
	}
	return nil
}

// ============ Heartbeat ============
type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_proto_gz14_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{10}
}

type HeartbeatRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRsp) Reset() {
	*x = HeartbeatRsp{}
	mi := &file_proto_gz14_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRsp) ProtoMessage() {}

func (x *HeartbeatRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRsp.ProtoReflect.Descriptor instead.
func (*HeartbeatRsp) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{11}
}

// ============ Scene: Move ============
type MoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveReq) Reset() {
	*x = MoveReq{}
	mi := &file_proto_gz14_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveReq) ProtoMessage() {}

func (x *MoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveReq.ProtoReflect.Descriptor instead.
func (*MoveReq) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{12}
}

func (x *MoveReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *MoveReq) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

type MoveBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Sequence      int32                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"` // 用于客户端检测丢包
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveBroadcast) Reset() {
	*x = MoveBroadcast{}
	mi := &file_proto_gz14_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveBroadcast) ProtoMessage() {}

func (x *MoveBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveBroadcast.ProtoReflect.Descriptor instead.
func (*MoveBroadcast) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{13}
}

func (x *MoveBroadcast) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *MoveBroadcast) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *MoveBroadcast) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// ============ Scene: AOI ============
type AOIEnter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerInfo          `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AOIEnter) Reset() {
	*x = AOIEnter{}
	mi := &file_proto_gz14_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AOIEnter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AOIEnter) ProtoMessage() {}

func (x *AOIEnter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AOIEnter.ProtoReflect.Descriptor instead.
func (*AOIEnter) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{14}
}

func (x *AOIEnter) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type AOILeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleIds       []int64                `protobuf:"varint,1,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AOILeave) Reset() {
	*x = AOILeave{}
	mi := &file_proto_gz14_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AOILeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AOILeave) ProtoMessage() {}

func (x *AOILeave) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AOILeave.ProtoReflect.Descriptor instead.
func (*AOILeave) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{15}
}

func (x *AOILeave) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// ============ Lobby: Logout ============
type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_proto_gz14_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{16}
}

func (x *LogoutReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       ErrCode                `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,enum=gz14.ErrCode" json:"err_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRsp) Reset() {
	*x = LogoutRsp{}
	mi := &file_proto_gz14_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRsp) ProtoMessage() {}

func (x *LogoutRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRsp.ProtoReflect.Descriptor instead.
func (*LogoutRsp) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{17}
}

func (x *LogoutRsp) GetErrCode() ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return ErrCode_ERR_OK
}

// ============ Reconnect ============
type ReconnectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectReq) Reset() {
	*x = ReconnectReq{}
	mi := &file_proto_gz14_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectReq) ProtoMessage() {}

func (x *ReconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectReq.ProtoReflect.Descriptor instead.
func (*ReconnectReq) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{18}
}

func (x *ReconnectReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReconnectReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type ReconnectRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       ErrCode                `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,enum=gz14.ErrCode" json:"err_code,omitempty"`
	MapId         int32                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	AoiPlayers    []*PlayerInfo          `protobuf:"bytes,4,rep,name=aoi_players,json=aoiPlayers,proto3" json:"aoi_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectRsp) Reset() {
	*x = ReconnectRsp{}
	mi := &file_proto_gz14_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectRsp) ProtoMessage() {}

func (x *ReconnectRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectRsp.ProtoReflect.Descriptor instead.
func (*ReconnectRsp) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{19}
}

func (x *ReconnectRsp) GetErrCode() ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return ErrCode_ERR_OK
}

func (x *ReconnectRsp) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ReconnectRsp) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ReconnectRsp) GetAoiPlayers() []*PlayerInfo {
	if x != nil {
		return x.AoiPlayers
	}
	return nil
}

// ============ Lobby → Scene internal ============
type PlayerEnterSceneNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	MapId         int32                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	PosX          float64                `protobuf:"fixed64,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float64                `protobuf:"fixed64,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEnterSceneNotify) Reset() {
	*x = PlayerEnterSceneNotify{}
	mi := &file_proto_gz14_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEnterSceneNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEnterSceneNotify) ProtoMessage() {}

func (x *PlayerEnterSceneNotify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEnterSceneNotify.ProtoReflect.Descriptor instead.
func (*PlayerEnterSceneNotify) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{20}
}

func (x *PlayerEnterSceneNotify) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *PlayerEnterSceneNotify) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *PlayerEnterSceneNotify) GetPosX() float64 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *PlayerEnterSceneNotify) GetPosY() float64 {
	if x != nil {
		return x.PosY
	}
	return 0
}

type PlayerLeaveSceneNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	MapId         int32                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeaveSceneNotify) Reset() {
	*x = PlayerLeaveSceneNotify{}
	mi := &file_proto_gz14_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeaveSceneNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeaveSceneNotify) ProtoMessage() {}

func (x *PlayerLeaveSceneNotify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gz14_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeaveSceneNotify.ProtoReflect.Descriptor instead.
func (*PlayerLeaveSceneNotify) Descriptor() ([]byte, []int) {
	return file_proto_gz14_proto_rawDescGZIP(), []int{21}
}

func (x *PlayerLeaveSceneNotify) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *PlayerLeaveSceneNotify) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

var File_proto_gz14_proto protoreflect.FileDescriptor

const file_proto_gz14_proto_rawDesc = "" +
	"\n" +
	"\x10proto/gz14.proto\x12\x04gz14\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\x85\x01\n" +
	"\n" +
	"PlayerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x15\n" +
	"\x06map_id\x18\x04 \x01(\x05R\x05mapId\x12&\n" +
	"\bposition\x18\x05 \x01(\v2\n" +
	".gz14.Vec2R\bposition\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x91\x01\n" +
	"\bLoginRsp\x12(\n" +
	"\berr_code\x18\x01 \x01(\x0e2\r.gz14.ErrCodeR\aerrCode\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"scene_addr\x18\x03 \x01(\tR\tsceneAddr\x12&\n" +
	"\x05roles\x18\x04 \x03(\v2\x10.gz14.PlayerInfoR\x05roles\"E\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"V\n" +
	"\vRegisterRsp\x12(\n" +
	"\berr_code\x18\x01 \x01(\x0e2\r.gz14.ErrCodeR\aerrCode\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\"9\n" +
	"\rCreateRoleReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"_\n" +
	"\rCreateRoleRsp\x12(\n" +
	"\berr_code\x18\x01 \x01(\x0e2\r.gz14.ErrCodeR\aerrCode\x12$\n" +
	"\x04role\x18\x02 \x01(\v2\x10.gz14.PlayerInfoR\x04role\">\n" +
	"\rEnterSceneReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\"\xab\x01\n" +
	"\rEnterSceneRsp\x12(\n" +
	"\berr_code\x18\x01 \x01(\x0e2\r.gz14.ErrCodeR\aerrCode\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x05R\x05mapId\x12&\n" +
	"\bposition\x18\x03 \x01(\v2\n" +
	".gz14.Vec2R\bposition\x121\n" +
	"\vaoi_players\x18\x04 \x03(\v2\x10.gz14.PlayerInfoR\n" +
	"aoiPlayers\"\x0e\n" +
	"\fHeartbeatReq\"\x0e\n" +
	"\fHeartbeatRsp\"J\n" +
	"\aMoveReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12&\n" +
	"\bposition\x18\x02 \x01(\v2\n" +
	".gz14.Vec2R\bposition\"l\n" +
	"\rMoveBroadcast\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12&\n" +
	"\bposition\x18\x02 \x01(\v2\n" +
	".gz14.Vec2R\bposition\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x05R\bsequence\"6\n" +
	"\bAOIEnter\x12*\n" +
	"\aplayers\x18\x01 \x03(\v2\x10.gz14.PlayerInfoR\aplayers\"%\n" +
	"\bAOILeave\x12\x19\n" +
	"\brole_ids\x18\x01 \x03(\x03R\aroleIds\"!\n" +
	"\tLogoutReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"5\n" +
	"\tLogoutRsp\x12(\n" +
	"\berr_code\x18\x01 \x01(\x0e2\r.gz14.ErrCodeR\aerrCode\"=\n" +
	"\fReconnectReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\"\xaa\x01\n" +
	"\fReconnectRsp\x12(\n" +
	"\berr_code\x18\x01 \x01(\x0e2\r.gz14.ErrCodeR\aerrCode\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x05R\x05mapId\x12&\n" +
	"\bposition\x18\x03 \x01(\v2\n" +
	".gz14.Vec2R\bposition\x121\n" +
	"\vaoi_players\x18\x04 \x03(\v2\x10.gz14.PlayerInfoR\n" +
	"aoiPlayers\"r\n" +
	"\x16PlayerEnterSceneNotify\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x05R\x05mapId\x12\x13\n" +
	"\x05pos_x\x18\x03 \x01(\x01R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x04 \x01(\x01R\x04posY\"H\n" +
	"\x16PlayerLeaveSceneNotify\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x05R\x05mapId*\xe3\x02\n" +
	"\aErrCode\x12\n" +
	"\n" +
	"\x06ERR_OK\x10\x00\x12\x10\n" +
	"\vERR_UNKNOWN\x10\xe8\a\x12\x14\n" +
	"\x0fERR_INVALID_MSG\x10\xe9\a\x12\x1a\n" +
	"\x15ERR_ACCOUNT_NOT_FOUND\x10\xd1\x0f\x12\x17\n" +
	"\x12ERR_WRONG_PASSWORD\x10\xd2\x0f\x12\x16\n" +
	"\x11ERR_ACCOUNT_EXIST\x10\xd3\x0f\x12\x18\n" +
	"\x13ERR_ROLE_NAME_EXIST\x10\xb9\x17\x12\x12\n" +
	"\rERR_ROLE_FULL\x10\xba\x17\x12\x17\n" +
	"\x12ERR_ROLE_NOT_FOUND\x10\xbb\x17\x12\x18\n" +
	"\x13ERR_SESSION_INVALID\x10\xa1\x1f\x12\x18\n" +
	"\x13ERR_SESSION_EXPIRED\x10\xa2\x1f\x12\x17\n" +
	"\x12ERR_LOGIN_REPEATED\x10\xa3\x1f\x12\x13\n" +
	"\x0eERR_SCENE_FULL\x10\x89'\x12\x16\n" +
	"\x11ERR_MOVE_TOO_FAST\x10\x8a'\x12\x16\n" +
	"\x11ERR_OUT_OF_BOUNDS\x10\x8b'B\x18Z\x16gz14/internal/protocolb\x06proto3"

var (
	file_proto_gz14_proto_rawDescOnce sync.Once
	file_proto_gz14_proto_rawDescData []byte
)

func file_proto_gz14_proto_rawDescGZIP() []byte {
	file_proto_gz14_proto_rawDescOnce.Do(func() {
		file_proto_gz14_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gz14_proto_rawDesc), len(file_proto_gz14_proto_rawDesc)))
	})
	return file_proto_gz14_proto_rawDescData
}

var file_proto_gz14_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gz14_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_gz14_proto_goTypes = []any{
	(ErrCode)(0),                   // 0: gz14.ErrCode
	(*Vec2)(nil),                   // 1: gz14.Vec2
	(*PlayerInfo)(nil),             // 2: gz14.PlayerInfo
	(*LoginReq)(nil),               // 3: gz14.LoginReq
	(*LoginRsp)(nil),               // 4: gz14.LoginRsp
	(*RegisterReq)(nil),            // 5: gz14.RegisterReq
	(*RegisterRsp)(nil),            // 6: gz14.RegisterRsp
	(*CreateRoleReq)(nil),          // 7: gz14.CreateRoleReq
	(*CreateRoleRsp)(nil),          // 8: gz14.CreateRoleRsp
	(*EnterSceneReq)(nil),          // 9: gz14.EnterSceneReq
	(*EnterSceneRsp)(nil),          // 10: gz14.EnterSceneRsp
	(*HeartbeatReq)(nil),           // 11: gz14.HeartbeatReq
	(*HeartbeatRsp)(nil),           // 12: gz14.HeartbeatRsp
	(*MoveReq)(nil),                // 13: gz14.MoveReq
	(*MoveBroadcast)(nil),          // 14: gz14.MoveBroadcast
	(*AOIEnter)(nil),               // 15: gz14.AOIEnter
	(*AOILeave)(nil),               // 16: gz14.AOILeave
	(*LogoutReq)(nil),              // 17: gz14.LogoutReq
	(*LogoutRsp)(nil),              // 18: gz14.LogoutRsp
	(*ReconnectReq)(nil),           // 19: gz14.ReconnectReq
	(*ReconnectRsp)(nil),           // 20: gz14.ReconnectRsp
	(*PlayerEnterSceneNotify)(nil), // 21: gz14.PlayerEnterSceneNotify
	(*PlayerLeaveSceneNotify)(nil), // 22: gz14.PlayerLeaveSceneNotify
}
var file_proto_gz14_proto_depIdxs = []int32{
	1,  // 0: gz14.PlayerInfo.position:type_name -> gz14.Vec2
	0,  // 1: gz14.LoginRsp.err_code:type_name -> gz14.ErrCode
	2,  // 2: gz14.LoginRsp.roles:type_name -> gz14.PlayerInfo
	0,  // 3: gz14.RegisterRsp.err_code:type_name -> gz14.ErrCode
	0,  // 4: gz14.CreateRoleRsp.err_code:type_name -> gz14.ErrCode
	2,  // 5: gz14.CreateRoleRsp.role:type_name -> gz14.PlayerInfo
	0,  // 6: gz14.EnterSceneRsp.err_code:type_name -> gz14.ErrCode
	1,  // 7: gz14.EnterSceneRsp.position:type_name -> gz14.Vec2
	2,  // 8: gz14.EnterSceneRsp.aoi_players:type_name -> gz14.PlayerInfo
	1,  // 9: gz14.MoveReq.position:type_name -> gz14.Vec2
	1,  // 10: gz14.MoveBroadcast.position:type_name -> gz14.Vec2
	2,  // 11: gz14.AOIEnter.players:type_name -> gz14.PlayerInfo
	0,  // 12: gz14.LogoutRsp.err_code:type_name -> gz14.ErrCode
	0,  // 13: gz14.ReconnectRsp.err_code:type_name -> gz14.ErrCode
	1,  // 14: gz14.ReconnectRsp.position:type_name -> gz14.Vec2
	2,  // 15: gz14.ReconnectRsp.aoi_players:type_name -> gz14.PlayerInfo
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_gz14_proto_init() }
func file_proto_gz14_proto_init() {
	if File_proto_gz14_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gz14_proto_rawDesc), len(file_proto_gz14_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gz14_proto_goTypes,
		DependencyIndexes: file_proto_gz14_proto_depIdxs,
		EnumInfos:         file_proto_gz14_proto_enumTypes,
		MessageInfos:      file_proto_gz14_proto_msgTypes,
	}.Build()
	File_proto_gz14_proto = out.File
	file_proto_gz14_proto_goTypes = nil
	file_proto_gz14_proto_depIdxs = nil
}
